### ISSUE TITLE
no voice recognized in demo

### ISSUE THREAD

**Issue by micahstubbs** [lmalave/aframe-voice-command-component#1]
couldn't get the demos to work from `Chrome 54 on a Mac` or `Aug 29 Chromium on Windows 10`  

used the built-in mic on the Mac and the Vive's microphone on the Windows machine  

tried both of the demos at [https://lmalave.github.io/aframe-voice-command-component/examples/index.html](https://lmalave.github.io/aframe-voice-command-component/examples/index.html) 

  🤔

**Comment by lmalave** [comment]
Thanks for your feedback!  If you could please let me know if you saw the following when you opened the examples, that would help me debug the issue:  
- Request to grant access to microphone
- Red dot in tab and camera icon in URL bar, indicating microphone has access

Images of both are attached.  Thanks again. 

![chrome_microphone_access_request](https://cloud.githubusercontent.com/assets/5093194/21504389/66b5ef9a-cc13-11e6-969a-12c2288d317d.png)

![chrome_microphone_status](https://cloud.githubusercontent.com/assets/5093194/21504376/42672bc2-cc13-11e6-985f-47cd3b76acbb.png)

**Comment by micahstubbs** [comment]
hi @lmalave, thanks for the reply.  

in both cases, I did click `allow` and see the red recording circle.  

I'll take a closer look and see if I can contribute a more helpful error report ☺

**Comment by micahstubbs** [comment]
got both the [Image Gallery](https://lmalave.github.io/aframe-voice-command-component/examples/image-gallery.html) and the [Teleport](https://lmalave.github.io/aframe-voice-command-component/examples/teleport.html) demo working 🎉 

I did two things:

+ I updated from Chrome 54 to Chrome 55 
(OS is `Mac OS X 10.11.6` El Capitan. that part stayed the same.)

+ selected a working microphone as the Mac OS sound input device by option+clicking on the volume icon >< 😅 

![screen shot 2016-12-27 at 6 45 42 pm](https://cloud.githubusercontent.com/assets/2119400/21512719/21b55d98-cc65-11e6-8aae-5e6293649154.png)

**Comment by micahstubbs** [comment]
by the way, thanks very much for add the troubleshooting info to the README. that gave the me the idea to update Chrome 😄
